import { CategoryType, MenuType } from "@src/types/website";
import Menu1 from "@src/assets/menus/kapi_phav.jpg";
import Menu2 from "@src/assets/menus/amok.jpg";
import Menu3 from "@src/assets/menus/nom_banh_jok.jpg";
import Menu4 from "@src/assets/menus/morn_bom_pong.jpg";

export const khmerFoodMenus: MenuType[] = [
  {
    menuId: 1,
    code: "KF001",
    nameEn: "Kapi Phav",
    nameKh: "កាពិផាវ",
    nameCn: "Kapi Phav",
    descriptionEn: "",
    descriptionKh: "",
    descriptionCn: "",
    price: 6.5,
    priceKh: 26000,
    discount: 10,
    status: 1,
    merchantId: null,
    categories: [],
    files: [
      {
        menuFileId: 1,
        fileName: "kapi_phav.jpg",
        filePath: Menu1,
        createdAt: null,
        updatedAt: null,
        main: true,
      },
    ],
    createdAt: null,
    updatedAt: null,
    hot: true,
  },
  {
    menuId: 2,
    code: "KF002",
    nameEn: "Amok",
    nameKh: "អាម៉ុក",
    nameCn: "Amok",
    descriptionEn: "",
    descriptionKh: "",
    descriptionCn: "",
    price: 4.5,
    priceKh: 18000,
    discount: 5,
    status: 1,
    merchantId: null,
    categories: [],
    files: [
      {
        menuFileId: 2,
        fileName: "amok.jpg",
        filePath: Menu2,
        createdAt: null,
        updatedAt: null,
        main: true,
      },
    ],
    createdAt: null,
    updatedAt: null,
    hot: true,
  },
  {
    menuId: 3,
    code: "KH003",
    nameEn: "Nom Banh Jok",
    nameKh: "នំបាញ់ចុក",
    nameCn: "Nom Banh Jok",
    descriptionEn: "",
    descriptionKh: "",
    descriptionCn: "",
    price: 2.5,
    priceKh: 10000,
    discount: 0,
    status: 1,
    merchantId: null,
    categories: [],
    files: [
      {
        menuFileId: 3,
        fileName: "nom_banh_jok.jpg",
        filePath: Menu3,
        createdAt: null,
        updatedAt: null,
        main: true,
      },
    ],
    createdAt: null,
    updatedAt: null,
    hot: true,
  },
  {
    menuId: 4,
    code: "KH004",
    nameEn: "Morn Bom Pong",
    nameKh: "	មាន់បំពង",
    nameCn: "Morn Bom Pong",
    descriptionEn: "",
    descriptionKh: "",
    descriptionCn: "",
    price: 7,
    priceKh: 28000,
    discount: 0,
    status: 1,
    merchantId: null,
    categories: [],
    files: [
      {
        menuFileId: 4,
        fileName: "morn_bom_pong.jpg",
        filePath: Menu4,
        createdAt: null,
        updatedAt: null,
        main: true,
      },
    ],
    createdAt: null,
    updatedAt: null,
    hot: true,
  },
];

export const staticCategories: CategoryType[] = [
  {
    categoryId: 1,
    nameEn: "Khmer Food",
    nameKh: "ម្ហូបខ្មែរ",
    nameCn: "高棉食品",
    status: 1,
    createdAt: null,
    updatedAt: null,
    displayOrder: 1,
    merchantId: null,
    menus: khmerFoodMenus,
  },
];
